### ISSUE TITLE
config log dump has some things backwards

### ISSUE THREAD

**Issue by pattivacek** [foundriesio/aktualizr-lite#118]
Saw this on a device I'm testing (with the server redacted):

```
[pacman]
type = "ostree+compose_apps"
os = ""
sysroot = ""
ostree_server = "[xxx]"
packages_file = "/usr/package.manifest"
fake_need_reboot = false
/var/sota/compose-apps = "compose_apps_root"
master = "tags"
```

This is from the log dump that happens when you run with loglevel 0. Notice anything funny? :) It's only the extra bits that aktualizr-lite adds that are backwards, so it looks like a bug here, but it could still somehow be in libaktualizr, I don't know.

**Comment by doanac** [comment]
This was fixed in libaktualizr - https://github.com/uptane/aktualizr/commit/d9abc9fc86a38f5ceba3d30bdff815f6f0c32098

**Comment by pattivacek** [comment]
Oops! Thanks. I forgot the dunfell branch is still using a slightly old version of libaktualizr.
