### ISSUE TITLE
writeCurrentTarget called after callback

### ISSUE THREAD

**Issue by mwasilew** [foundriesio/aktualizr-lite#138]
writeCurrentTarget is called after callback. This means that containers receiving callback might use the outdated information from 'current-target' file.
https://github.com/foundriesio/aktualizr-lite/blob/21349f19e837c363e85b4a0aac1fb5e47bd3aabf/src/liteclient.cc#L264

**Comment by doanac** [comment]
@mike-sul - i keep not getting this done. can you take a quick look? it's a "one-liner".

**Comment by mike-sul** [comment]
https://github.com/foundriesio/aktualizr-lite/pull/141

**Comment by MrCry0** [comment]
@doanac the issue is still open although the #141  is merged.
